name: quran_contest_app
description: Quran Contest Management MVP - Cross Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  supabase_flutter: ^2.12.4
  shared_preferences: ^2.5.5
  file_picker: ^11.0.2
  image: ^4.8.0
  printing: ^5.14.3
  pdf: ^3.12.0
  syncfusion_flutter_xlsio: ^33.2.5
  syncfusion_officechart: ^33.2.5
  path_provider: ^2.1.5
  path: ^1.9.0
  url_launcher: ^6.2.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/images/logo_musapaka_rounded.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/images/logo_musapaka_rounded.png"
  image_path: "assets/images/logo_musapaka_rounded.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Variable.ttf
